import Earring_Model from "./Earring_Model";

export default (products = []) => {
    const all_Products = products;

    const item_1 = Earring_Model(11, { name: 'YFBH עגילי יהלום', carat: '2.4 קראט' }, "עגילי יהלום נופלים זהב  ב-18 יהלומים מושלמים במשקל 0.18", { tipe: 'QDE151076-18KY :סגנון', material: 'מתכת: זהב צהוב 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 2.4 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://bgjewelers.com/wp-content/uploads/2016/07/bge3.mp4?_=2', 16500.0001);
    const item_2 = Earring_Model(12, { name: 'VGTD עגילי יהלום', carat: '1.5 קראט' }, "הצמד היהלומים המושלם הזה משובץ שיבוץ שיניים על גבי 14K זהב. שיטת שיבוץ זו מאפשרת לאור לחדור ליהלום מכל כיוון והוא בתמורה ממקסם את כמות הנצנוצים שלו.", { tipe: 'BE2DE15103-18KY :סגנון', material: 'מתכת: זהב צהוב 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.5 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://bgjewelers.com/wp-content/uploads/2016/07/BGE11.mp4?_=2', 12500.0001);
    const item_3 = Earring_Model(13, { name: 'YUTD עגילי יהלום', carat: '2 קראט' }, ", בעדינות ובאלגנטת, עגילי יהלומים אלה כוללים 150 יהלומים עגולים בשיבוץ מיוחד על גבי זהב 14 .", { tipe: 'ME2DE15105-18KY :סגנון', material: 'מתכת: זהב לבן 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 2 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, ' https://bgjewelers.com/wp-content/uploads/2016/07/bge4.mp4?_=2', 17500.0001);
    const item_4 = Earring_Model(14, { name: 'HYGT עגילי יהלום', carat: '1.6 קראט' }, "עגילים משובחים אלה כוללים את היהלום המרכזי שנבחר, מעוטרים בהילה של יהלומים קטנים משובצים בסגנו ", { tipe: 'SE2DE15199-18KY :סגנון', material: 'מתכת: זהב צהוב 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.6 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://bgjewelers.com/wp-content/uploads/2016/07/bge2.mp4?_=2', 14500.0001);
    const item_5 = Earring_Model(15, { name: 'OJDY עגילי יהלום', carat: '0.9 קראט' }, "זוג עגילי יהלום בצורה פרינסס על גבי 14K זהב לבן או לבן. העגילים צמודים לאוזן, נוחים לענידה ואלגנטיים במיוחד.", { tipe: 'GE2DE1532-18KY :סגנון', material: 'מתכת: זהב לבן 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 0.9 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://bgjewelers.com/wp-content/uploads/2016/07/BGE5.mp4?_=2', 11500.0001);
    const item_6 = Earring_Model(16, { name: 'RFDT עגילי יהלום', carat: '1.7 קראט' }, "עגילי יהלומים בזהב ורוד 18 קראט (7.52 גרם) עם יהלומים (0.3600 קראט)", { tipe: 'UR2DE15151-18KY :סגנון', material: 'מתכת: זהב רוז 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.7 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://kinvid0.bluestone.com/output/mp4/BISK0364H09-VIDEO-22795.mp4/BISK0364H09-VIDEO-22795.mp4', 15000.0001);
    const item_7 = Earring_Model(17, { name: 'HFYF עגילי יהלום', carat: '2.1 קראט' }, " עגילי יהלומים בזהב ורוד 18 קראט (4.96 גרם) עם יהלומים (0.1260 קראט)", { tipe: 'OU2DE1584-18KY :סגנון', material: 'מתכת: זהב רוז 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 2.1 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://kinvid1.bluestone.com/output/mp4/BINK0363S11-VIDEO-20149.mp4/BINK0363S11-VIDEO-20149.mp4', 17500.0001);
    const item_8 = Earring_Model(18, { name: 'IDYD עגילי יהלום', carat: '1.5 קראט' }, "  העלה העדין ביותר עם האבנים המהממות ביותר - לקחנו את חתיך הפרחים והפכנו אותו למיני, עם כל עלי כותרת של יהלומים על גבעול זהב. החלק הטוב ביותר בו שהוא בפריחה כל השנה..", { tipe: 'FE2DE15103-18KY :סגנון', material: 'מתכת: זהב צהוב 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.5 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://kinvid0.bluestone.com/output/mp4/BIVT0055S12-VIDEO-3981.mp4/BIVT0055S12-VIDEO-3981.mp4', 13500.0001);
    const item_9 = Earring_Model(19, { name: 'BRYR עגילי יהלום', carat: '1.3 קראט' }, "עגילי יהלום אלה יראו לך את הדרך למעלה. עם 58 (0.75 קראט) יהלומים לבנים בוהקים על גבי זהב 14k לבן. הרגע הזה שאת נכנסת לחדר וכולם מסתכלים אליך מהסיבות הנכונות. עגילים מרשימים ויוצאי דופן שישדרגו לך כל יציאה..", { tipe: 'YT2DE151-18KY :סגנון', material: 'מתכת: זהב לבן 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.3 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://kinvid1.bluestone.com/output/mp4/BISD0102S05-VIDEO-4116.mp4/BISD0102S05-VIDEO-4116.mp4', 12000.0001);
    const item_10 = Earring_Model(20, { name: 'DJND עגילי יהלום', carat: '1.8 קראט' }, "עגילי חישוק המציגים מעגל שלם משובץ יהלומים. בעגילי יהלום אלה משובצים לא פחות מ-14 יהלומים לבנים מרהיבים במשקל 0.60 קראט המשובצים שיבוץ שיניים על גבי חישוקי 14K זהב צהוב, שיטת שיבוץ זו מאפשרת לכל יהלום ויהלום לנצנץ בצורה מרבית. עגילים יוקרתיים באיכות גבוהה במיוחד", { tipe: 'JY2DE1654-18KY :סגנון', material: 'מתכת: זהב צהוב 18 קראט', Average_Width: 'רוחב ממוצע: 3.1 מ"מ ', weight: 'משקל כולל: 1.8 קראט', color: 'E :בהירות יהלום', clarity: 'VS-1 :נקיות יהלום' }, 'https://kinvid0.bluestone.com/output/mp4/BIPM0001H05-VIDEO-4736.mp4/BIPM0001H05-VIDEO-4736.mp4 ', 16700.0001);

    const Earring_Products = [item_1, item_2, item_3, item_4, item_5, item_6, item_7, item_8, item_9, item_10];

    Earring_Products.map((value) => {
        all_Products.push(value);
    })
    return all_Products;
}
